In [1]:
import numpy as np 
import pandas as pd 
import pickle 
from collections import defaultdict

In [2]:
vata_hpids = pd.read_csv('D:/learning/HPOA dataset/GitHub uploads/market_basket_analysis/vata_mba/MBA_vata_phenotypes.csv', index_col= 0)
vata_hpids

    Phenotype_ID
0     HP:0000036
1     HP:0000045
2     HP:0000217
3     HP:0000360
4     HP:0000364
..           ...
129   HP:0100785
130   HP:0100813
131   HP:0100872
132   HP:0200025
133   HP:0200026

[134 rows x 1 columns]

In [3]:
def pickle_load(file_path):
    with open(file_path, 'rb') as handle:
        b = pickle.load(handle)
    return b

In [4]:
# hpo_disease_dict = pickle_load('D:\learning\HPOA dataset\GitHub uploads\Final_concnecous\Version_110923\pickled_dictonary_version110923\hpo_disease_dict_V_160923.pickle')
# #
# disease_hpo_dict = pickle_load('D:\learning\HPOA dataset\GitHub uploads\Final_concnecous\data_retrival\disease_hpo_dict_V_110923.pickle')
# hpid_descriptions_dict = pickle_load('D:\learning\HPOA dataset\GitHub uploads\Final_concnecous\Version_110923\pickled_dictonary_version110923\hpid_descriptions_dict_V_110923.pickle')

In [5]:
%run "D:\learning\HPOA dataset\GitHub uploads\Final_concnecous\dictonary_making\hpo_disease_dict_making.ipynb"

In [6]:
# hpo_disease_dict['HP:0000496']

In [7]:
vata_disease_with_names_df = pd.read_excel('D:\learning\HPOA dataset\GitHub uploads\Final_concnecous\data_retrival\Vata_disease_with_names.xlsx', index_col= 0)
vata_disease_with_names_df

,Disease_ID,Disease_Name,HP_ID
0,OMIM:618076,['Neurodevelopmental disorder with spasticity ...,HP:0000496
1,OMIM:618249,"['Mitochondrial complex I deficiency, nuclear ...",HP:0000496
2,OMIM:618088,"['Neurodevelopmental disorder with regression,...",HP:0000496
3,OMIM:617622,['Joubert syndrome 30'],HP:0000496
4,OMIM:300966,"['Mental retardation, X-linked, syndromic 33']",HP:0000496
...,...,...,...
11820,ORPHA:71211,['Neuromyelitis optica spectrum disorder'],HP:0200026
11821,ORPHA:94058,['Neovascular glaucoma'],HP:0200026
11822,ORPHA:293381,['Epithelial recurrent erosion dystrophy'],HP:0200026
11823,ORPHA:280914,['Idiopathic anterior uveitis'],HP:0200026
11824,ORPHA:280921,['Idiopathic panuveitis'],HP:0200026

In [8]:
vata_disease_df = vata_disease_with_names_df['Disease_ID']
vata_disease_df = vata_disease_df.drop_duplicates()
vata_disease_df.size

6423

In [9]:
vata_disease_with_names_df_for_dict = vata_disease_with_names_df.drop(columns=['Disease_Name'])
# [['Disease_ID', 'HP_ID']]
vata_disease_with_names_df_for_dict

         Disease_ID       HP_ID
0       OMIM:618076  HP:0000496
1       OMIM:618249  HP:0000496
2       OMIM:618088  HP:0000496
3       OMIM:617622  HP:0000496
4       OMIM:300966  HP:0000496
...             ...         ...
11820   ORPHA:71211  HP:0200026
11821   ORPHA:94058  HP:0200026
11822  ORPHA:293381  HP:0200026
11823  ORPHA:280914  HP:0200026
11824  ORPHA:280921  HP:0200026

[11825 rows x 2 columns]

In [10]:
nanatmaj_vata_disease_hpid_dict = defaultdict(list)
nanatmaj_vata_hpid_disease_dict = defaultdict(list)

# Iterate over the DataFrame
for index, row in vata_disease_with_names_df_for_dict.iterrows():
    HP_ID = row['HP_ID']
    Disease_ID = row['Disease_ID']
    
    # Convert the HP_ID to a string before using it as a key
    nanatmaj_vata_disease_hpid_dict[str(Disease_ID)].append(HP_ID)

In [11]:
# nanatmaj_vata_disease_hpid_dict

In [12]:
# Iterate over the DataFrame
for index, row in vata_disease_with_names_df_for_dict.iterrows():
    HP_ID = row['HP_ID']
    Disease_ID = row['Disease_ID']
    
    # Convert the HP_ID to a string before using it as a key
    nanatmaj_vata_hpid_disease_dict[str(HP_ID)].append(Disease_ID)

In [13]:
# nanatmaj_vata_hpid_disease_dict

In [14]:
def creating_dataframe_from_disease_to_hpid_dict(input_dict):
    return

In [15]:
from collections import defaultdict
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [16]:


# Sample data as a defaultdict
# data = defaultdict(list)
# data['Document1'] = ['A', 'B', 'C']
# data['Document2'] = ['B', 'C', 'D']
# data['Document3'] = ['A', 'C']
# data['Document4'] = ['A', 'B', 'D']

data = nanatmaj_vata_disease_hpid_dict

# Convert the defaultdict to a list of lists for DataFrame creation
data_list = list(nanatmaj_vata_disease_hpid_dict.values())

In [17]:
def pickle_save(file_name, dict_name):
    with open(file_name, 'wb') as handle:
        pickle.dump(dict_name, handle, protocol=pickle.HIGHEST_PROTOCOL)

In [19]:
pickle_save('nanatmaj_vata_disease_hpid_dict_v180923.pickle', nanatmaj_vata_disease_hpid_dict)

In [148]:
# row_list  =

In [149]:
# Create a DataFrame from the data
df = pd.DataFrame(columns=vata_disease_with_names_df_for_dict["HP_ID"].drop_duplicates(), index=data.keys())

df

HP_ID,HP:0000496,HP:0025264,HP:0000217,HP:0000360,HP:0000364,HP:0004409,HP:0000458,HP:0000508,HP:0000504,HP:0000643,...,HP:0040264,HP:0100247,HP:0031051,HP:0006607,HP:0011001,HP:0100679,HP:0100785,HP:0000045,HP:0100813,HP:0000036
OMIM:618076,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OMIM:618249,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OMIM:618088,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OMIM:617622,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OMIM:300966,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ORPHA:64755,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ORPHA:457083,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ORPHA:3339,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ORPHA:139466,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ORPHA:1756,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [150]:
for x in vata_disease_with_names_df_for_dict["Disease_ID"]:
    temp_hpo_list = nanatmaj_vata_disease_hpid_dict[x]
    for y in temp_hpo_list:
        df[y][x] = 1

In [151]:
df  = df.fillna(0)
df

HP_ID,HP:0000496,HP:0025264,HP:0000217,HP:0000360,HP:0000364,HP:0004409,HP:0000458,HP:0000508,HP:0000504,HP:0000643,...,HP:0040264,HP:0100247,HP:0031051,HP:0006607,HP:0011001,HP:0100679,HP:0100785,HP:0000045,HP:0100813,HP:0000036
OMIM:618076,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
OMIM:618249,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
OMIM:618088,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
OMIM:617622,1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
OMIM:300966,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ORPHA:64755,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
ORPHA:457083,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
ORPHA:3339,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
ORPHA:139466,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
ORPHA:1756,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

Select top 3 supports and perforn the MBA                       

find the main cloud and the surropunding cloud

In [152]:
# Perform Apriori analysis to find frequent itemsets
min_support =0.005  # Adjust the minimum support as needed
frequent_itemsets = apriori(df, min_support=min_support, use_colnames=True)

frequent_itemsets

     support                              itemsets
0   0.015413                          (HP:0000496)
1   0.007317                          (HP:0000217)
2   0.009341                          (HP:0000360)
3   0.007162                          (HP:0000364)
4   0.009809                          (HP:0000458)
..       ...                                   ...
84  0.005605              (HP:0003270, HP:0002027)
85  0.007006              (HP:0002167, HP:0004322)
86  0.020863              (HP:0001762, HP:0004322)
87  0.012300  (HP:0000508, HP:0004322, HP:0001250)
88  0.006695  (HP:0004322, HP:0001762, HP:0001250)

[89 rows x 2 columns]

In [153]:
frequent_itemsets.to_excel('frequent_itemsets_with_min_support_' + str(min_support) + '_.xlsx')

In [154]:
# type(frequent_itemsets[['itemsets']].iloc[100,0])

In [155]:
disease_cloud = []
disease_set = []
for i in range (len(frequent_itemsets[['itemsets']])):
    phenotype_id_list = frequent_itemsets[['itemsets']].iloc[i,0]
    # phenotype_id = list(phenotype_id)
    # print(type(phenotype_id))
    # break
    temp_disease_set = set()
    temp_disease_list = []
    for phenotype_id in  phenotype_id_list:
        # print('for ',phenotype_id)
        temp_disease_list.append(hpo_disease_dict[phenotype_id])
        # print('disease: ',hpo_disease_dict[phenotype_id])
        # print('list: ',temp_disease_list)
        # temp_disease_set.add(hpo_disease_dict[phenotype_id])
        

    # x = list(phenotype)
    temp_disease_list = [element for innerList in temp_disease_list for element in innerList]
    temp_disease_list = [temp_disease_list[n] for n in range(len(temp_disease_list)) if n == temp_disease_list.index(temp_disease_list[n]) ]
    # print(temp_disease_list)
    disease_cloud.append(temp_disease_list)
    # disease_set.append(temp_disease_set)
    # temp_disease_list.clear()

    # break
    # for phenotype in x:
    #     print(x)


# frequent_itemsets[['itemsets']]

In [156]:
print(len(disease_cloud))

89

In [157]:
# frequent_itemsets[['disease_cloud']] = disease_cloud
se = pd.Series(disease_cloud)
frequent_itemsets['disease_cloud'] = se
frequent_itemsets

,support,itemsets,disease_cloud
0,0.015413,(HP:0000496),"[OMIM:618076, OMIM:618249, OMIM:618088, OMIM:6..."
1,0.007317,(HP:0000217),"[OMIM:180920, OMIM:100100, OMIM:133020, OMIM:6..."
2,0.009341,(HP:0000360),"[OMIM:605594, OMIM:606705, OMIM:613079, OMIM:4..."
3,0.007162,(HP:0000364),"[OMIM:186570, OMIM:613849, OMIM:169170, OMIM:6..."
4,0.009809,(HP:0000458),"[OMIM:610628, OMIM:614842, OMIM:603457, OMIM:6..."
...,...,...,...
84,0.005605,"(HP:0003270, HP:0002027)","[OMIM:277900, OMIM:226150, OMIM:155310, OMIM:6..."
85,0.007006,"(HP:0002167, HP:0004322)","[OMIM:231000, OMIM:609636, OMIM:221770, OMIM:2..."
86,0.020863,"(HP:0001762, HP:0004322)","[OMIM:615546, OMIM:256850, OMIM:616503, OMIM:2..."
87,0.012300,"(HP:0000508, HP:0004322, HP:0001250)","[OMIM:615546, OMIM:211500, OMIM:113620, OMIM:2..."
88,0.006695,"(HP:0004322, HP:0001762, HP:0001250)","[OMIM:615220, OMIM:618076, OMIM:300431, OMIM:6..."

In [158]:
frequent_itemsets.to_excel('frequent_itemsets_with_min_support_' + str(min_support) + '_alongwith_corresp_disease_id.xlsx')